# NumPy Excercise

In [115]:
import numpy as np

Conditional Filtering: Create a 5x5 matrix with random float values between 0 and 1. Replace all values greater than 0.5 with 1 and the rest with 0.


In [116]:
arr = np.random.rand(5, 5)
print(arr)
arr[arr > 0.5] = 1
arr[arr <= 0.5] = 0
arr

[[0.42650633 0.91261872 0.0181192  0.33089804 0.14263288]
 [0.21711938 0.85064389 0.02228879 0.11827933 0.95748616]
 [0.52773721 0.5370063  0.4259822  0.81404148 0.32872195]
 [0.41993218 0.89469664 0.02906848 0.27254781 0.57564081]
 [0.20785195 0.68135907 0.69637732 0.54932766 0.56750295]]


array([[0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 1.],
       [1., 1., 0., 1., 0.],
       [0., 1., 0., 0., 1.],
       [0., 1., 1., 1., 1.]])

Statistical Analysis: Create a 1000-element array with random integer values between 50 and 150. Compute the following:

The mean, median, and standard deviation of the array.
The percentage of elements greater than 100.

In [117]:
from scipy import stats

Array Creation

In [118]:
arr = np.random.randint(low=50, high=150, size=1000).reshape(10, 100)

Mean Median Mode

In [119]:
print(f"Mean of the array is {np.mean(arr)}")
print(f"Median of the array is {np.median(arr)}")
print(f"Mode of the array is {stats.mode(arr,axis=None,keepdims=True)}")

Mean of the array is 98.3
Median of the array is 97.0
Mode of the array is ModeResult(mode=array([70]), count=array([21]))


Percentage of element greather than 100

In [120]:
arr_greather_100 = arr[arr > 100]
(arr_greather_100.size * 100) / 1000

45.6

Broadcasting Practice: Create a 3x4 matrix with random integers between 1 and 10. Subtract the mean of each row from each element in that row using broadcasting.

In [121]:
arr = np.random.randint(low=1, high=10, size=(3, 4))
print(arr)
mean_row = arr.mean(axis=1)
print(mean_row)
arr - mean_row.reshape(arr.shape[0], -1)

[[3 6 5 1]
 [1 4 6 8]
 [9 6 6 4]]
[3.75 4.75 6.25]


array([[-0.75,  2.25,  1.25, -2.75],
       [-3.75, -0.75,  1.25,  3.25],
       [ 2.75, -0.25, -0.25, -2.25]])

Masking and Indexing: Generate a 6x6 array with random integers between 10 and 100. Find and replace all even numbers with their negative value.



In [122]:
arr = np.random.randint(low=10, high=100, size=(6, 6))
arr[arr % 2 == 0] *= -1
arr

array([[-96,  41, -34,  11,  73,  27],
       [-42, -58, -42, -10, -40, -76],
       [ 59,  67,  37, -36,  53,  53],
       [-72, -82,  85,  51,  35, -38],
       [ 61, -70, -18, -74, -34, -10],
       [-74,  21, -66,  47,  15, -30]])

Advanced Slicing

In [123]:
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12],
                  [13, 14, 15, 16]])

The subarray containing the middle 2x2 section. <br>

In [124]:
row = array.shape[0]
col = array.shape[1]
row_start, row_end = (row//2)-1, (row//2)+1
col_start, col_end = (col//2)-1, (col//2)+1

In [125]:
array[row_start:row_end, col_start:col_end]

array([[ 6,  7],
       [10, 11]])

The elements on the diagonal of the array.

In [126]:
for i in range(array.shape[0]):
    print(array[i][i])

1
6
11
16


Reverse the array along its second axis.

In [127]:
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [128]:
np.flip(array, axis=1)

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9],
       [16, 15, 14, 13]])

Unique Elements and Counting: Create a 1D array with 50 random integers between 1 and 10. Find the unique elements in the array and count their occurrences.

In [129]:
arr = np.random.randint(low=1, high=10, size=50)
arr

array([8, 8, 5, 6, 9, 7, 7, 2, 5, 1, 6, 1, 3, 1, 2, 5, 8, 7, 5, 3, 6, 8,
       5, 3, 1, 9, 3, 5, 5, 2, 9, 1, 5, 9, 9, 9, 5, 7, 8, 2, 1, 6, 8, 4,
       1, 3, 2, 7, 4, 3])

In [130]:
np.unique(arr, return_counts=True)

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([7, 5, 6, 2, 9, 4, 5, 6, 6], dtype=int64))

Random Sampling: Generate a 1D array of 15 random integers between 1 and 20. Pick 5 random elements from this array without replacement.

In [131]:
arr = np.random.randint(low=1, high=20, size=15)
np.random.choice(arr, replace=False, size=5)

array([ 1,  8,  6, 19,  3])

Dot Product and Vectorization: Create two 1D arrays a and b with 20 random integer values between 1 and 100. Compute their dot product using:

A for loop.
NumPy's built-in dot function. Verify that both methods yield the same result.

In [132]:
a = np.random.randint(low=1, high=100, size=20)
b = np.random.randint(low=1, high=100, size=20)
c = np.zeros(20)

In [133]:
a, b

(array([77, 59, 22, 24, 47, 84, 54, 52, 90, 37, 18, 78, 35, 38, 36, 59,  8,
        30, 86, 24]),
 array([34, 51, 19, 46, 36, 12, 70, 82, 19, 45, 32, 92, 49,  9, 29,  3, 54,
        87, 84, 88]))

In [134]:
s = 0
for i in range(20):
    s += a[i] * b[i]
s

44676

In [135]:
np.dot(a, b)

44676

Advanced Matrix Manipulation: Create a 4x4 matrix M with random integers between 10 and 50. Perform the following operations:

Swap the first and last rows of the matrix.

Create Array

In [136]:
arr = np.random.randint(low=10, high=50, size=(4, 4))
arr

array([[28, 39, 22, 35],
       [14, 33, 38, 11],
       [49, 17, 11, 10],
       [30, 41, 16, 45]])

In [137]:
arr[0, :], arr[-1, :] = arr[-1, :].copy(), arr[0, :].copy()

In [138]:
arr

array([[30, 41, 16, 45],
       [14, 33, 38, 11],
       [49, 17, 11, 10],
       [28, 39, 22, 35]])

Rotate the matrix 90 degrees clockwise.


Using Loop

In [139]:
matrix = np.array([
    [46, 46, 35, 46],
    [48, 44, 24, 38],
    [42, 35, 17, 31],
    [22, 47, 14, 36]
])
# result:
#     [22, 42, 48, 46],
#     [47, 35, 44, 46],
#     [14, 17, 24, 35],
#     [36, 31, 38, 46]

rotated_matrix = np.zeros((4, 4), dtype=int)

num_rows = matrix.shape[0]
num_cols = matrix.shape[1]

for row in range(num_rows):
    for col in range(num_cols):
        rotated_matrix[col][(num_rows - 1) - row] = matrix[row][col]

rotated_matrix

array([[22, 42, 48, 46],
       [47, 35, 44, 46],
       [14, 17, 24, 35],
       [36, 31, 38, 46]])

Using Methods

In [140]:
matrix.T

array([[46, 48, 42, 22],
       [46, 44, 35, 47],
       [35, 24, 17, 14],
       [46, 38, 31, 36]])

In [141]:
np.flip(matrix.T, axis=1)

array([[22, 42, 48, 46],
       [47, 35, 44, 46],
       [14, 17, 24, 35],
       [36, 31, 38, 46]])


Set the diagonal elements to zero without modifying other elements.

In [142]:
for i in range(arr.shape[0]):
    arr[i][i] = 0
arr

array([[ 0, 41, 16, 45],
       [14,  0, 38, 11],
       [49, 17,  0, 10],
       [28, 39, 22,  0]])

Complex Indexing: Generate a 7x7 matrix of random integers between 1 and 100. Extract all elements that form the border (i.e., the first and last rows and columns).

In [143]:
arr = np.random.randint(low=1, high=100, size=(7, 7))
arr

array([[87, 82, 72, 51, 21, 67, 41],
       [49,  8, 48, 99,  6, 65, 69],
       [57, 14, 80, 91, 28, 66, 89],
       [89, 60, 14,  3, 60, 11, 78],
       [40, 55, 14, 14, 55, 47, 16],
       [99, 40, 70, 56, 26, 81, 20],
       [10, 52, 54, 70, 46, 45, 63]])

In [144]:
arr[0, :], arr[-1, :], arr[:, 0], arr[:, -1]

(array([87, 82, 72, 51, 21, 67, 41]),
 array([10, 52, 54, 70, 46, 45, 63]),
 array([87, 49, 57, 89, 40, 99, 10]),
 array([41, 69, 89, 78, 16, 20, 63]))

Row and Column Operations: Create a 5x5 matrix with random integers between 1 and 20. Normalize each column such that the sum of each column is 1. (Hint: Use broadcasting for efficient computation.)

num - min / max - min

##### Normalize

In [145]:
arr = np.random.randint(low=1, high=20, size=(5, 5))
arr

array([[ 1, 11,  2, 17, 12],
       [10, 11, 15, 11, 18],
       [ 6, 15, 18, 15, 11],
       [17,  6, 17, 17, 14],
       [14,  3,  1,  5,  8]])

In [146]:
arr1 = np.zeros(shape=(5, 5))

In [147]:
arr1 = (arr - arr.min(axis=0)) / (arr.max(axis=0) - arr.min(axis=0))

In [148]:
arr1

array([[0.        , 0.66666667, 0.05882353, 1.        , 0.4       ],
       [0.5625    , 0.66666667, 0.82352941, 0.5       , 1.        ],
       [0.3125    , 1.        , 1.        , 0.83333333, 0.3       ],
       [1.        , 0.25      , 0.94117647, 1.        , 0.6       ],
       [0.8125    , 0.        , 0.        , 0.        , 0.        ]])

####

In [149]:
index = 5
shape = (3, 4)
print(np.unravel_index(index, shape, order='C'))

(1, 1)


In [150]:
flat_index = np.array([5, 6, 11])  # flat indices
shape = (3, 4)  # 3 rows and 4 columns
print(np.unravel_index(flat_index, shape, order='C'))

(array([1, 1, 2], dtype=int64), array([1, 2, 3], dtype=int64))


Multiple Axis Stacking: Given three 1D arrays of the same length, arr1, arr2, and arr3, stack them along both the first and second axis to form a 3D array. Explain the difference between stacking along axis 0 and axis 1.

In [151]:
arr1 = np.arange(start=10, stop=20)
arr2 = np.arange(start=20, stop=30)
arr3 = np.arange(start=30, stop=40)

In [152]:
np.stack([arr1, arr2, arr3], axis=0)

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [153]:
np.stack([arr1, arr2, arr3], axis=1)

array([[10, 20, 30],
       [11, 21, 31],
       [12, 22, 32],
       [13, 23, 33],
       [14, 24, 34],
       [15, 25, 35],
       [16, 26, 36],
       [17, 27, 37],
       [18, 28, 38],
       [19, 29, 39]])

Custom Array Re-stacking: Given a 3D array of shape (2, 3, 4), stack slices of the array along a new axis to reshape it into (3, 2, 4, 1). How does the shape of the output change with each axis parameter in np.stack?

In [154]:
array = np.array([6, 4])
print(array)
sum_of_elements = np.sum(array)
print(sum_of_elements)

[6 4]
10


In [155]:
arr1 = np.arange(start=10, stop=30).reshape(4, 5)
arr2 = np.arange(start=30, stop=50).reshape(4, 5)

In [156]:
arr1, arr2

(array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]),
 array([[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]))

In [157]:
np.vstack([arr1, arr2])

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [158]:
np.hstack([arr1, arr2])

array([[10, 11, 12, 13, 14, 30, 31, 32, 33, 34],
       [15, 16, 17, 18, 19, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 40, 41, 42, 43, 44],
       [25, 26, 27, 28, 29, 45, 46, 47, 48, 49]])

Squeeze (remove single dimension)

Removing Single Dimensions: Given a 3D array of shape (3, 1, 4), use squeeze to remove the single dimension. Verify the result by checking the shape of the output array.

In [159]:
arr = np.arange(start=10, stop=30).reshape(1, 4, 1, 5)
arr

array([[[[10, 11, 12, 13, 14]],

        [[15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24]],

        [[25, 26, 27, 28, 29]]]])

In [160]:
np.squeeze(arr)

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [161]:
arr.squeeze()

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

Sliding Window Questions


1D Sliding Window Sum: Create a function that, given a 1D array arr and a window size k, returns an array of the sums of each sliding window. Test the function with arr = [1, 2, 3, 4, 5, 6] and k = 3.

In [162]:
arr = [1, 2, 3, 4, 5, 6]
k = 3

In [163]:
np.cumsum(arr)

array([ 1,  3,  6, 10, 15, 21])

In [164]:
np.cumprod(arr)

array([  1,   2,   6,  24, 120, 720])

In [165]:
for i in range(0, len(arr), k):
    print(sum(arr[i:k+i]))

6
15


2D Sliding Window Mean: Given a 2D array arr of shape (5, 5), write a function to calculate the mean of all 2x2 sliding windows. How does the number of windows vary with different 2D shapes?

In [166]:
arr = np.arange(start=10, stop=35).reshape(5, 5)
for i in range(4):
    for j in range(4):
        print(arr[i:i+2, j:j+2].mean())

13.0
14.0
15.0
16.0
18.0
19.0
20.0
21.0
23.0
24.0
25.0
26.0
28.0
29.0
30.0
31.0


In [167]:
import pandas as pd

# Sample DataFrame
data = {
    'A': [1, 2, 3, 4, 5],
    'B': [5, 4, 3, 2, 1],
    'C': [10, 9, 8, 7, 6]
}
df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

# Using pd.where to replace values in column 'A' that are less than 3 with NaN
# df['A'] = df['A'].where(df['A'] >= 3)
df['A'] = df['A'][df['A']>= 3]

print("\nDataFrame after applying pd.where:")
print(df)


Original DataFrame:
   A  B   C
0  1  5  10
1  2  4   9
2  3  3   8
3  4  2   7
4  5  1   6

DataFrame after applying pd.where:
     A  B   C
0  NaN  5  10
1  NaN  4   9
2  3.0  3   8
3  4.0  2   7
4  5.0  1   6


In [168]:
# Sample DataFrame
data = {
    'A': [1, 2, 3, 4, 5],
    'B': [5, 4, 3, 2, 1],
    'C': [10, 9, 8, 7, 6]
}
df = pd.DataFrame(data)
df['A'] = df['A'][df['A']>= 3]

print("\nDataFrame after applying pd.where:")
print(df)


DataFrame after applying pd.where:
     A  B   C
0  NaN  5  10
1  NaN  4   9
2  3.0  3   8
3  4.0  2   7
4  5.0  1   6


In [169]:
# Sample DataFrame
data = {
    'A': [1, 2, 3, 4, 5],
    'B': [5, 4, 3, 2, 1],
    'C': [10, 9, 8, 7, 6]
}
df = pd.DataFrame(data)
# print(df['A'])
df.apply(lambda x : x if x['A'] == 1 else x['A'] + 1,axis=1)

A  B   C
0  1  5  10
1  3  3   3
2  4  4   4
3  5  5   5
4  6  6   6